version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    versioning-strategy: auto

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    versioning-strategy: auto

