name: 'release-dcl'
description: 'Test gh action for releasing'
author: 'Manuel Mena'
inputs:
  GITHUB_TOKEN:
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: arrow-right
  color: green