name: 'release'
on: [workflow_dispatch]

jobs:
  release: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: result
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "Github context ${{ steps.result.outputs.context}}"
      - run: echo "Reoi ${{ steps.result.outputs.repository}}"
      - run: echo "Owner login ${{ steps.result.outputs.owner}}"
      # - run: echo "Last tag ${{ steps.result.outputs.lastTag}}"
      # - run: echo "Commits found ${{ steps.result.outputs.commitsLength}}"
      # - run: echo "Major being bumped ${{ steps.result.outputs.bumpMajor}}"
      # - run: echo "Minor being bumped ${{ steps.result.outputs.bumpMinor}}"
      # - run: echo "Patch being bumped ${{ steps.result.outputs.bumpPatch}}"
      # - run: echo "New tag ${{ steps.result.outputs.newTag}}"