name: 'build'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      # - run: |
      #     npm run all
  dry-run: # make a dry-run to test it
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: result
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          repository: ${{ github.repository }}
